[tox]
envlist = towncrier-check,docs{,-lint,-all},package,py{310,311,312,313,314}
skip_missing_interpreters = true

[testenv]
dependency_groups = test
commands =
    python -m pytest {posargs:-vv --color yes}

[testenv:towncrier{,-check}]
dependency_groups = towncrier
commands =
    check  : python -m towncrier.check --compare-with origin/main
    !check : python -m towncrier {posargs}

[docs]
docs_dir = {tox_root}{/}docs

[testenv:docs{,-lint,-links,-all,-live,-serve}]
# Docs are always built on Python 3.13. See also the RTD config.
base_python = py313
package = wheel
wheel_build_env = .pkg
dependency_groups = docs
passenv =
    READTHEDOCS_CANONICAL_URL
setenv =
    DISABLE_MKDOCS_2_WARNING = true
    NO_MKDOCS_2_WARNING = 1
commands =
    !lint-!links-!all-!live-!serve : build_md_translations {posargs} --source-code=src en
    all  : build_md_translations {posargs} --source-code=src en
    live : live_serve_en {posargs} src --port=8044 --source-code=src
    lint : pyspelling
    links : markdown-checker --dir {tox_root}{/}docs{/}en --func check_broken_urls
    serve : python -m http.server -d _build/html 8045
